### PR TITLE
Fix readme formatting

### PR DESCRIPTION
**Pull request by bjschafer**

### CODE REVIEW

**Comment by Tyko7** [comment]
I'm in, I believe.

**Comment by bjschafer** [comment]
Sort of! Click the chat button on the main page and then you'll be super in.

**Comment by Tyko7** [comment]
Where is the chat button?

**Comment by bjschafer** [comment]
If you click on 1v1me on top there's a chat button, but you can click [here](https://gitter.im/bjschafer/1v1me?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) also

**Pull request merged**
